### PR TITLE
Try to make perf improve

### PR DESCRIPTION
**Pull request by wdv4758h**

### CODE REVIEW

**Comment by wdv4758h** [comment]
um, forget to pull the new master

**Comment by wdv4758h** [comment]
um, wha't wrong with the CI
error

**Comment by mre** [comment]
Sorry, guess it was my fault with https://github.com/mre/hyperjson/commit/3a35e1adebe095e20b47389ad4ea7ed89ed99982
Can you uncomment the cdylib line and commit that to this branch?
Lesson learned: will always go through a PR now. 😅

**Comment by wdv4758h** [comment]
I just notice that when you reply :smile:

**Comment by mre** [comment]
In my local tests I can't see a big performance improvement yet. Actually the values are a bit worse compared to before. Now I know that this should not be the case and I guess the benchmark code is just very inaccurate. Therefore I created #18 to port the benchmarks to pytest-benchmark.

In any case, your change looks good and I think we should merge it, because we avoid a `to_string()` operation (and there can be lots of them). So +1 from my side!
Thanks!

**Comment by wdv4758h** [comment]
I think `pytest-benchmark` will be a good one, really love the pytest ecosystem, awesome tools and easy to install.

**Pull request merged**
