### PR TITLE
WIP: Experiment with pyo3-pack

### PR DESCRIPTION
**Pull request by mre**

### CODE REVIEW

**Comment by konstin** [comment]
Great to see adoption of pyo3-pack! Just some general notes: I'd recommend installing with pip, especially on ci (I've changed the readme to make that a bit clearer). I'd also recommend either completely keeping or completely discarding the setuptools and buildwheel config; The current state leaves a non-functional setup.py.

**Comment by mre** [comment]
Right. I'll clean up the setup.py and buildwheel config once I get around to it. Thanks for the hint.
pyo3-pack is really cool.

**Comment by mre** [comment]
Plan is to release hyperjson to pypi with it (the first release!).

**Comment by mre** [comment]
@konstin, any final comments before merging? :smiley:

**Comment by konstin** [comment]
Looks good! :+1:

**Pull request merged**
